apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-network-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: ingress-nginx
        applabel: app.kubernetes.io/component=controller
        appkind: deployment
    chaosServiceAccount: pod-network-duplication-sa
    experiments:
        - name: pod-network-duplication-ingress-nginx-controller-controller
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: controller
