apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: monitoring
        applabel: app.kubernetes.io/part-of=kube-prometheus-stack
        appkind: deployment
    chaosServiceAccount: container-kill-sa
    experiments:
        - name: container-kill-kube-prometheus-stack-operator-kube-prometheus-stack
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: kube-prometheus-stack
