apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: cert-manager
        applabel: app=webhook
        appkind: deployment
    chaosServiceAccount: pod-io-stress-sa
    experiments:
        - name: pod-io-stress-cert-manager-webhook-cert-manager
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: cert-manager
