apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: cert-manager
        applabel: app.kubernetes.io/component=webhook
        appkind: deployment
    chaosServiceAccount: pod-io-stress-sa
    experiments:
        - name: pod-io-stress
          spec:
            components:
                env:
                    - name: TOTAL_CHAOS_DURATION
                      value: "120"
                    - name: FILESYSTEM_UTILIZATION_PERCENTAGE
                      value: "10"
                    - name: CONTAINER_RUNTIME
                      value: docker
                    - name: SOCKET_PATH
                      value: /var/run/docker.sock
