apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: monitoring
        applabel: alertmanager=kube-prometheus-stack-alertmanager
        appkind: statefulset
    chaosServiceAccount: ""
    experiments: []
