apiVersion: ""
kind: ""
metadata:
    name: pod-mem-hog-alertmanager-kube-prometheus-stack-alertmanager-alertmanager
    labels:
        name: ""
        app.kubernetes.io/part-of: ""
        app.kubernetes.io/component: ""
        app.kubernetes.io/version: ""
spec:
    definition:
        scope: ""
        permissions: []
        image: ""
        imagePullPolicy: ""
        args: []
        command: []
        env: []
        labels:
            name: ""
            app.kubernetes.io/part-of: ""
            app.kubernetes.io/component: ""
            app.kubernetes.io/version: ""
