apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: monitoring
        applabel: app.kubernetes.io/instance=kube-prometheus-stack-prometheus
        appkind: statefulset
    chaosServiceAccount: pod-cpu-hog-exec-sa
    experiments:
        - name: pod-cpu-hog-prometheus-kube-prometheus-stack-prometheus-prometheus
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: prometheus
