apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: litmus
        applabel: app.kubernetes.io/component=litmus-frontend
        appkind: deployment
    chaosServiceAccount: pod-cpu-hog-exec-sa
    experiments:
        - name: pod-cpu-hog-litmusportal-frontend-litmusportal-frontend
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: litmusportal-frontend
