apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: monitoring
        applabel: app.kubernetes.io/name=kube-state-metrics
        appkind: deployment
    chaosServiceAccount: ""
    experiments: []
