apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: litmus
        applabel: app=mongo
        appkind: statefulset
    chaosServiceAccount: ""
    experiments:
        - name: pod-mem-hog-litmusportal-mongo-mongo
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: mongo
