apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
    name: /home/robin/.kube/config-kube-system
    version: 0.1.16
    annotations:
        categories: Kubernetes
        vendor: ""
        support: ""
spec:
    displayName: /home/robin/.kube/config-kube-system
    experiments:
        - container-kill-coredns-coredns
        - pod-delete-coredns
        - pod-cpu-hog-coredns-coredns
        - pod-mem-hog-coredns-coredns
        - pod-io-stress-coredns-coredns
        - pod-network-corruption-coredns-coredns
        - pod-network-duplication-coredns-coredns
        - pod-network-loss-coredns-coredns
        - pod-network-latency-coredns-coredns
    categoryDescription: |
        Kubernetes is an open-source system for automating deployment, scaling, and management of containerized applications. It groups containers that make up an application into logical units for easier management and discovery. It will install all the experiments which can be used to inject chaos into containerized applications.
    keywords: []
    platforms: []
    maturity: ""
    chaosType: ""
    maintainers:
        - name: ksatchit
          email: karthik.s@mayadata.io
    minKubeVersion: 1.12.0
    provider:
        name: Mayadata
    labels:
        app.kubernetes.io/component: ""
        app.kubernetes.io/version: ""
    links:
        - name: Kubernetes Website
          url: https://kubernetes.io
        - name: Source Code
          url: https://github.com/kubernetes/kubernetes
        - name: Kubernetes Slack
          url: https://slack.kubernetes.io/
        - name: Documentation
          url: https://litmuschaos.github.io/litmus/experiments/categories/contents/#generic
    icon:
        - url: https://raw.githubusercontent.com/litmuschaos/charthub.litmuschaos.io/master/public/litmus.ico
          mediatype: image/png
    chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/experiments.yaml
