apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-network-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: cert-manager
        applabel: app.kubernetes.io/component=cainjector
        appkind: deployment
    chaosServiceAccount: pod-network-corruption-sa
    experiments:
        - name: pod-network-corruption-cert-manager-cainjector-cert-manager
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: cert-manager
