apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: litmus
        applabel: app=workflow-controller
        appkind: deployment
    chaosServiceAccount: pod-delete-sa
    experiments:
        - name: pod-delete-workflow-controller
          spec:
            components:
                env: []
