apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: litmus
        applabel: app.kubernetes.io/version=latest
        appkind: deployment
    chaosServiceAccount: ""
    experiments:
        - name: pod-cpu-hog-chaos-operator-ce-chaos-operator
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: chaos-operator
