apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: litmus
        applabel: app=chaos-exporter
        appkind: deployment
    chaosServiceAccount: ""
    experiments:
        - name: pod-mem-hog-chaos-exporter-chaos-exporter
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: chaos-exporter
