- 45
- 45
- 45
- 10
- 97
- 112
- 105
- 86
- 101
- 114
- 115
- 105
- 111
- 110
- 58
- 32
- 118
- 49
- 10
- 107
- 105
- 110
- 100
- 58
- 32
- 83
- 101
- 114
- 118
- 105
- 99
- 101
- 65
- 99
- 99
- 111
- 117
- 110
- 116
- 10
- 109
- 101
- 116
- 97
- 100
- 97
- 116
- 97
- 58
- 10
- 32
- 32
- 110
- 97
- 109
- 101
- 58
- 32
- 112
- 111
- 100
- 45
- 105
- 111
- 45
- 115
- 116
- 114
- 101
- 115
- 115
- 45
- 115
- 97
- 10
- 32
- 32
- 110
- 97
- 109
- 101
- 115
- 112
- 97
- 99
- 101
- 58
- 32
- 100
- 101
- 102
- 97
- 117
- 108
- 116
- 10
- 32
- 32
- 108
- 97
- 98
- 101
- 108
- 115
- 58
- 10
- 32
- 32
- 32
- 32
- 110
- 97
- 109
- 101
- 58
- 32
- 112
- 111
- 100
- 45
- 105
- 111
- 45
- 115
- 116
- 114
- 101
- 115
- 115
- 45
- 115
- 97
- 10
- 32
- 32
- 32
- 32
- 97
- 112
- 112
- 46
- 107
- 117
- 98
- 101
- 114
- 110
- 101
- 116
- 101
- 115
- 46
- 105
- 111
- 47
- 112
- 97
- 114
- 116
- 45
- 111
- 102
- 58
- 32
- 108
- 105
- 116
- 109
- 117
- 115
- 10
- 45
- 45
- 45
- 10
- 97
- 112
- 105
- 86
- 101
- 114
- 115
- 105
- 111
- 110
- 58
- 32
- 114
- 98
- 97
- 99
- 46
- 97
- 117
- 116
- 104
- 111
- 114
- 105
- 122
- 97
- 116
- 105
- 111
- 110
- 46
- 107
- 56
- 115
- 46
- 105
- 111
- 47
- 118
- 49
- 10
- 107
- 105
- 110
- 100
- 58
- 32
- 82
- 111
- 108
- 101
- 10
- 109
- 101
- 116
- 97
- 100
- 97
- 116
- 97
- 58
- 10
- 32
- 32
- 110
- 97
- 109
- 101
- 58
- 32
- 112
- 111
- 100
- 45
- 105
- 111
- 45
- 115
- 116
- 114
- 101
- 115
- 115
- 45
- 115
- 97
- 10
- 32
- 32
- 110
- 97
- 109
- 101
- 115
- 112
- 97
- 99
- 101
- 58
- 32
- 100
- 101
- 102
- 97
- 117
- 108
- 116
- 10
- 32
- 32
- 108
- 97
- 98
- 101
- 108
- 115
- 58
- 10
- 32
- 32
- 32
- 32
- 110
- 97
- 109
- 101
- 58
- 32
- 112
- 111
- 100
- 45
- 105
- 111
- 45
- 115
- 116
- 114
- 101
- 115
- 115
- 45
- 115
- 97
- 10
- 32
- 32
- 32
- 32
- 97
- 112
- 112
- 46
- 107
- 117
- 98
- 101
- 114
- 110
- 101
- 116
- 101
- 115
- 46
- 105
- 111
- 47
- 112
- 97
- 114
- 116
- 45
- 111
- 102
- 58
- 32
- 108
- 105
- 116
- 109
- 117
- 115
- 10
- 114
- 117
- 108
- 101
- 115
- 58
- 10
- 32
- 32
- 35
- 32
- 67
- 114
- 101
- 97
- 116
- 101
- 32
- 97
- 110
- 100
- 32
- 109
- 111
- 110
- 105
- 116
- 111
- 114
- 32
- 116
- 104
- 101
- 32
- 101
- 120
- 112
- 101
- 114
- 105
- 109
- 101
- 110
- 116
- 32
- 38
- 32
- 104
- 101
- 108
- 112
- 101
- 114
- 32
- 112
- 111
- 100
- 115
- 10
- 32
- 32
- 45
- 32
- 97
- 112
- 105
- 71
- 114
- 111
- 117
- 112
- 115
- 58
- 32
- 91
- 34
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 114
- 101
- 115
- 111
- 117
- 114
- 99
- 101
- 115
- 58
- 32
- 91
- 34
- 112
- 111
- 100
- 115
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 118
- 101
- 114
- 98
- 115
- 58
- 32
- 91
- 34
- 99
- 114
- 101
- 97
- 116
- 101
- 34
- 44
- 34
- 100
- 101
- 108
- 101
- 116
- 101
- 34
- 44
- 34
- 103
- 101
- 116
- 34
- 44
- 34
- 108
- 105
- 115
- 116
- 34
- 44
- 34
- 112
- 97
- 116
- 99
- 104
- 34
- 44
- 34
- 117
- 112
- 100
- 97
- 116
- 101
- 34
- 44
- 32
- 34
- 100
- 101
- 108
- 101
- 116
- 101
- 99
- 111
- 108
- 108
- 101
- 99
- 116
- 105
- 111
- 110
- 34
- 93
- 10
- 32
- 32
- 35
- 32
- 80
- 101
- 114
- 102
- 111
- 114
- 109
- 115
- 32
- 67
- 82
- 85
- 68
- 32
- 111
- 112
- 101
- 114
- 97
- 116
- 105
- 111
- 110
- 115
- 32
- 111
- 110
- 32
- 116
- 104
- 101
- 32
- 101
- 118
- 101
- 110
- 116
- 115
- 32
- 105
- 110
- 115
- 105
- 100
- 101
- 32
- 99
- 104
- 97
- 111
- 115
- 101
- 110
- 103
- 105
- 110
- 101
- 32
- 97
- 110
- 100
- 32
- 99
- 104
- 97
- 111
- 115
- 114
- 101
- 115
- 117
- 108
- 116
- 10
- 32
- 32
- 45
- 32
- 97
- 112
- 105
- 71
- 114
- 111
- 117
- 112
- 115
- 58
- 32
- 91
- 34
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 114
- 101
- 115
- 111
- 117
- 114
- 99
- 101
- 115
- 58
- 32
- 91
- 34
- 101
- 118
- 101
- 110
- 116
- 115
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 118
- 101
- 114
- 98
- 115
- 58
- 32
- 91
- 34
- 99
- 114
- 101
- 97
- 116
- 101
- 34
- 44
- 34
- 103
- 101
- 116
- 34
- 44
- 34
- 108
- 105
- 115
- 116
- 34
- 44
- 34
- 112
- 97
- 116
- 99
- 104
- 34
- 44
- 34
- 117
- 112
- 100
- 97
- 116
- 101
- 34
- 93
- 10
- 32
- 32
- 35
- 32
- 70
- 101
- 116
- 99
- 104
- 32
- 99
- 111
- 110
- 102
- 105
- 103
- 109
- 97
- 112
- 115
- 32
- 100
- 101
- 116
- 97
- 105
- 108
- 115
- 32
- 97
- 110
- 100
- 32
- 109
- 111
- 117
- 110
- 116
- 32
- 105
- 116
- 32
- 116
- 111
- 32
- 116
- 104
- 101
- 32
- 101
- 120
- 112
- 101
- 114
- 105
- 109
- 101
- 110
- 116
- 32
- 112
- 111
- 100
- 32
- 40
- 105
- 102
- 32
- 115
- 112
- 101
- 99
- 105
- 102
- 105
- 101
- 100
- 41
- 10
- 32
- 32
- 45
- 32
- 97
- 112
- 105
- 71
- 114
- 111
- 117
- 112
- 115
- 58
- 32
- 91
- 34
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 114
- 101
- 115
- 111
- 117
- 114
- 99
- 101
- 115
- 58
- 32
- 91
- 34
- 99
- 111
- 110
- 102
- 105
- 103
- 109
- 97
- 112
- 115
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 118
- 101
- 114
- 98
- 115
- 58
- 32
- 91
- 34
- 103
- 101
- 116
- 34
- 44
- 34
- 108
- 105
- 115
- 116
- 34
- 44
- 93
- 10
- 32
- 32
- 35
- 32
- 84
- 114
- 97
- 99
- 107
- 32
- 97
- 110
- 100
- 32
- 103
- 101
- 116
- 32
- 116
- 104
- 101
- 32
- 114
- 117
- 110
- 110
- 101
- 114
- 44
- 32
- 101
- 120
- 112
- 101
- 114
- 105
- 109
- 101
- 110
- 116
- 44
- 32
- 97
- 110
- 100
- 32
- 104
- 101
- 108
- 112
- 101
- 114
- 32
- 112
- 111
- 100
- 115
- 32
- 108
- 111
- 103
- 32
- 10
- 32
- 32
- 45
- 32
- 97
- 112
- 105
- 71
- 114
- 111
- 117
- 112
- 115
- 58
- 32
- 91
- 34
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 114
- 101
- 115
- 111
- 117
- 114
- 99
- 101
- 115
- 58
- 32
- 91
- 34
- 112
- 111
- 100
- 115
- 47
- 108
- 111
- 103
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 118
- 101
- 114
- 98
- 115
- 58
- 32
- 91
- 34
- 103
- 101
- 116
- 34
- 44
- 34
- 108
- 105
- 115
- 116
- 34
- 44
- 34
- 119
- 97
- 116
- 99
- 104
- 34
- 93
- 32
- 32
- 10
- 32
- 32
- 35
- 32
- 102
- 111
- 114
- 32
- 99
- 114
- 101
- 97
- 116
- 105
- 110
- 103
- 32
- 97
- 110
- 100
- 32
- 109
- 97
- 110
- 97
- 103
- 105
- 110
- 103
- 32
- 116
- 111
- 32
- 101
- 120
- 101
- 99
- 117
- 116
- 101
- 32
- 99
- 111
- 109
- 97
- 110
- 100
- 115
- 32
- 105
- 110
- 115
- 105
- 100
- 101
- 32
- 116
- 97
- 114
- 103
- 101
- 116
- 32
- 99
- 111
- 110
- 116
- 97
- 105
- 110
- 101
- 114
- 10
- 32
- 32
- 45
- 32
- 97
- 112
- 105
- 71
- 114
- 111
- 117
- 112
- 115
- 58
- 32
- 91
- 34
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 114
- 101
- 115
- 111
- 117
- 114
- 99
- 101
- 115
- 58
- 32
- 91
- 34
- 112
- 111
- 100
- 115
- 47
- 101
- 120
- 101
- 99
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 118
- 101
- 114
- 98
- 115
- 58
- 32
- 91
- 34
- 103
- 101
- 116
- 34
- 44
- 34
- 108
- 105
- 115
- 116
- 34
- 44
- 34
- 99
- 114
- 101
- 97
- 116
- 101
- 34
- 93
- 10
- 32
- 32
- 35
- 32
- 100
- 101
- 114
- 105
- 118
- 105
- 110
- 103
- 32
- 116
- 104
- 101
- 32
- 112
- 97
- 114
- 101
- 110
- 116
- 47
- 111
- 119
- 110
- 101
- 114
- 32
- 100
- 101
- 116
- 97
- 105
- 108
- 115
- 32
- 111
- 102
- 32
- 116
- 104
- 101
- 32
- 112
- 111
- 100
- 40
- 105
- 102
- 32
- 112
- 97
- 114
- 101
- 110
- 116
- 32
- 105
- 115
- 32
- 97
- 110
- 121
- 111
- 102
- 32
- 123
- 100
- 101
- 112
- 108
- 111
- 121
- 109
- 101
- 110
- 116
- 44
- 32
- 115
- 116
- 97
- 116
- 101
- 102
- 117
- 108
- 115
- 101
- 116
- 44
- 32
- 100
- 97
- 101
- 109
- 111
- 110
- 115
- 101
- 116
- 115
- 125
- 41
- 10
- 32
- 32
- 45
- 32
- 97
- 112
- 105
- 71
- 114
- 111
- 117
- 112
- 115
- 58
- 32
- 91
- 34
- 97
- 112
- 112
- 115
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 114
- 101
- 115
- 111
- 117
- 114
- 99
- 101
- 115
- 58
- 32
- 91
- 34
- 100
- 101
- 112
- 108
- 111
- 121
- 109
- 101
- 110
- 116
- 115
- 34
- 44
- 34
- 115
- 116
- 97
- 116
- 101
- 102
- 117
- 108
- 115
- 101
- 116
- 115
- 34
- 44
- 34
- 114
- 101
- 112
- 108
- 105
- 99
- 97
- 115
- 101
- 116
- 115
- 34
- 44
- 32
- 34
- 100
- 97
- 101
- 109
- 111
- 110
- 115
- 101
- 116
- 115
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 118
- 101
- 114
- 98
- 115
- 58
- 32
- 91
- 34
- 108
- 105
- 115
- 116
- 34
- 44
- 34
- 103
- 101
- 116
- 34
- 93
- 10
- 32
- 32
- 35
- 32
- 100
- 101
- 114
- 105
- 118
- 105
- 110
- 103
- 32
- 116
- 104
- 101
- 32
- 112
- 97
- 114
- 101
- 110
- 116
- 47
- 111
- 119
- 110
- 101
- 114
- 32
- 100
- 101
- 116
- 97
- 105
- 108
- 115
- 32
- 111
- 102
- 32
- 116
- 104
- 101
- 32
- 112
- 111
- 100
- 40
- 105
- 102
- 32
- 112
- 97
- 114
- 101
- 110
- 116
- 32
- 105
- 115
- 32
- 100
- 101
- 112
- 108
- 111
- 121
- 109
- 101
- 110
- 116
- 67
- 111
- 110
- 102
- 105
- 103
- 41
- 32
- 32
- 10
- 32
- 32
- 45
- 32
- 97
- 112
- 105
- 71
- 114
- 111
- 117
- 112
- 115
- 58
- 32
- 91
- 34
- 97
- 112
- 112
- 115
- 46
- 111
- 112
- 101
- 110
- 115
- 104
- 105
- 102
- 116
- 46
- 105
- 111
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 114
- 101
- 115
- 111
- 117
- 114
- 99
- 101
- 115
- 58
- 32
- 91
- 34
- 100
- 101
- 112
- 108
- 111
- 121
- 109
- 101
- 110
- 116
- 99
- 111
- 110
- 102
- 105
- 103
- 115
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 118
- 101
- 114
- 98
- 115
- 58
- 32
- 91
- 34
- 108
- 105
- 115
- 116
- 34
- 44
- 34
- 103
- 101
- 116
- 34
- 93
- 10
- 32
- 32
- 35
- 32
- 100
- 101
- 114
- 105
- 118
- 105
- 110
- 103
- 32
- 116
- 104
- 101
- 32
- 112
- 97
- 114
- 101
- 110
- 116
- 47
- 111
- 119
- 110
- 101
- 114
- 32
- 100
- 101
- 116
- 97
- 105
- 108
- 115
- 32
- 111
- 102
- 32
- 116
- 104
- 101
- 32
- 112
- 111
- 100
- 40
- 105
- 102
- 32
- 112
- 97
- 114
- 101
- 110
- 116
- 32
- 105
- 115
- 32
- 100
- 101
- 112
- 108
- 111
- 121
- 109
- 101
- 110
- 116
- 67
- 111
- 110
- 102
- 105
- 103
- 41
- 10
- 32
- 32
- 45
- 32
- 97
- 112
- 105
- 71
- 114
- 111
- 117
- 112
- 115
- 58
- 32
- 91
- 34
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 114
- 101
- 115
- 111
- 117
- 114
- 99
- 101
- 115
- 58
- 32
- 91
- 34
- 114
- 101
- 112
- 108
- 105
- 99
- 97
- 116
- 105
- 111
- 110
- 99
- 111
- 110
- 116
- 114
- 111
- 108
- 108
- 101
- 114
- 115
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 118
- 101
- 114
- 98
- 115
- 58
- 32
- 91
- 34
- 103
- 101
- 116
- 34
- 44
- 34
- 108
- 105
- 115
- 116
- 34
- 93
- 10
- 32
- 32
- 35
- 32
- 100
- 101
- 114
- 105
- 118
- 105
- 110
- 103
- 32
- 116
- 104
- 101
- 32
- 112
- 97
- 114
- 101
- 110
- 116
- 47
- 111
- 119
- 110
- 101
- 114
- 32
- 100
- 101
- 116
- 97
- 105
- 108
- 115
- 32
- 111
- 102
- 32
- 116
- 104
- 101
- 32
- 112
- 111
- 100
- 40
- 105
- 102
- 32
- 112
- 97
- 114
- 101
- 110
- 116
- 32
- 105
- 115
- 32
- 97
- 114
- 103
- 111
- 45
- 114
- 111
- 108
- 108
- 111
- 117
- 116
- 115
- 41
- 10
- 32
- 32
- 45
- 32
- 97
- 112
- 105
- 71
- 114
- 111
- 117
- 112
- 115
- 58
- 32
- 91
- 34
- 97
- 114
- 103
- 111
- 112
- 114
- 111
- 106
- 46
- 105
- 111
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 114
- 101
- 115
- 111
- 117
- 114
- 99
- 101
- 115
- 58
- 32
- 91
- 34
- 114
- 111
- 108
- 108
- 111
- 117
- 116
- 115
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 118
- 101
- 114
- 98
- 115
- 58
- 32
- 91
- 34
- 108
- 105
- 115
- 116
- 34
- 44
- 34
- 103
- 101
- 116
- 34
- 93
- 10
- 32
- 32
- 35
- 32
- 102
- 111
- 114
- 32
- 99
- 111
- 110
- 102
- 105
- 103
- 117
- 114
- 105
- 110
- 103
- 32
- 97
- 110
- 100
- 32
- 109
- 111
- 110
- 105
- 116
- 111
- 114
- 32
- 116
- 104
- 101
- 32
- 101
- 120
- 112
- 101
- 114
- 105
- 109
- 101
- 110
- 116
- 32
- 106
- 111
- 98
- 32
- 98
- 121
- 32
- 116
- 104
- 101
- 32
- 99
- 104
- 97
- 111
- 115
- 45
- 114
- 117
- 110
- 110
- 101
- 114
- 32
- 112
- 111
- 100
- 10
- 32
- 32
- 45
- 32
- 97
- 112
- 105
- 71
- 114
- 111
- 117
- 112
- 115
- 58
- 32
- 91
- 34
- 98
- 97
- 116
- 99
- 104
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 114
- 101
- 115
- 111
- 117
- 114
- 99
- 101
- 115
- 58
- 32
- 91
- 34
- 106
- 111
- 98
- 115
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 118
- 101
- 114
- 98
- 115
- 58
- 32
- 91
- 34
- 99
- 114
- 101
- 97
- 116
- 101
- 34
- 44
- 34
- 108
- 105
- 115
- 116
- 34
- 44
- 34
- 103
- 101
- 116
- 34
- 44
- 34
- 100
- 101
- 108
- 101
- 116
- 101
- 34
- 44
- 34
- 100
- 101
- 108
- 101
- 116
- 101
- 99
- 111
- 108
- 108
- 101
- 99
- 116
- 105
- 111
- 110
- 34
- 93
- 10
- 32
- 32
- 35
- 32
- 102
- 111
- 114
- 32
- 99
- 114
- 101
- 97
- 116
- 105
- 111
- 110
- 44
- 32
- 115
- 116
- 97
- 116
- 117
- 115
- 32
- 112
- 111
- 108
- 108
- 105
- 110
- 103
- 32
- 97
- 110
- 100
- 32
- 100
- 101
- 108
- 101
- 116
- 105
- 111
- 110
- 32
- 111
- 102
- 32
- 108
- 105
- 116
- 109
- 117
- 115
- 32
- 99
- 104
- 97
- 111
- 115
- 32
- 114
- 101
- 115
- 111
- 117
- 114
- 99
- 101
- 115
- 32
- 117
- 115
- 101
- 100
- 32
- 119
- 105
- 116
- 104
- 105
- 110
- 32
- 97
- 32
- 99
- 104
- 97
- 111
- 115
- 32
- 119
- 111
- 114
- 107
- 102
- 108
- 111
- 119
- 10
- 32
- 32
- 45
- 32
- 97
- 112
- 105
- 71
- 114
- 111
- 117
- 112
- 115
- 58
- 32
- 91
- 34
- 108
- 105
- 116
- 109
- 117
- 115
- 99
- 104
- 97
- 111
- 115
- 46
- 105
- 111
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 114
- 101
- 115
- 111
- 117
- 114
- 99
- 101
- 115
- 58
- 32
- 91
- 34
- 99
- 104
- 97
- 111
- 115
- 101
- 110
- 103
- 105
- 110
- 101
- 115
- 34
- 44
- 34
- 99
- 104
- 97
- 111
- 115
- 101
- 120
- 112
- 101
- 114
- 105
- 109
- 101
- 110
- 116
- 115
- 34
- 44
- 34
- 99
- 104
- 97
- 111
- 115
- 114
- 101
- 115
- 117
- 108
- 116
- 115
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 118
- 101
- 114
- 98
- 115
- 58
- 32
- 91
- 34
- 99
- 114
- 101
- 97
- 116
- 101
- 34
- 44
- 34
- 108
- 105
- 115
- 116
- 34
- 44
- 34
- 103
- 101
- 116
- 34
- 44
- 34
- 112
- 97
- 116
- 99
- 104
- 34
- 44
- 34
- 117
- 112
- 100
- 97
- 116
- 101
- 34
- 44
- 34
- 100
- 101
- 108
- 101
- 116
- 101
- 34
- 93
- 10
- 32
- 32
- 35
- 32
- 117
- 115
- 101
- 32
- 108
- 105
- 116
- 109
- 117
- 115
- 32
- 112
- 115
- 112
- 10
- 32
- 32
- 45
- 32
- 97
- 112
- 105
- 71
- 114
- 111
- 117
- 112
- 115
- 58
- 32
- 91
- 34
- 112
- 111
- 108
- 105
- 99
- 121
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 114
- 101
- 115
- 111
- 117
- 114
- 99
- 101
- 115
- 58
- 32
- 91
- 34
- 112
- 111
- 100
- 115
- 101
- 99
- 117
- 114
- 105
- 116
- 121
- 112
- 111
- 108
- 105
- 99
- 105
- 101
- 115
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 118
- 101
- 114
- 98
- 115
- 58
- 32
- 91
- 34
- 117
- 115
- 101
- 34
- 93
- 10
- 32
- 32
- 32
- 32
- 114
- 101
- 115
- 111
- 117
- 114
- 99
- 101
- 78
- 97
- 109
- 101
- 115
- 58
- 32
- 91
- 34
- 108
- 105
- 116
- 109
- 117
- 115
- 34
- 93
- 10
- 45
- 45
- 45
- 10
- 97
- 112
- 105
- 86
- 101
- 114
- 115
- 105
- 111
- 110
- 58
- 32
- 114
- 98
- 97
- 99
- 46
- 97
- 117
- 116
- 104
- 111
- 114
- 105
- 122
- 97
- 116
- 105
- 111
- 110
- 46
- 107
- 56
- 115
- 46
- 105
- 111
- 47
- 118
- 49
- 10
- 107
- 105
- 110
- 100
- 58
- 32
- 82
- 111
- 108
- 101
- 66
- 105
- 110
- 100
- 105
- 110
- 103
- 10
- 109
- 101
- 116
- 97
- 100
- 97
- 116
- 97
- 58
- 10
- 32
- 32
- 110
- 97
- 109
- 101
- 58
- 32
- 112
- 111
- 100
- 45
- 105
- 111
- 45
- 115
- 116
- 114
- 101
- 115
- 115
- 45
- 115
- 97
- 10
- 32
- 32
- 110
- 97
- 109
- 101
- 115
- 112
- 97
- 99
- 101
- 58
- 32
- 100
- 101
- 102
- 97
- 117
- 108
- 116
- 10
- 32
- 32
- 108
- 97
- 98
- 101
- 108
- 115
- 58
- 10
- 32
- 32
- 32
- 32
- 110
- 97
- 109
- 101
- 58
- 32
- 112
- 111
- 100
- 45
- 105
- 111
- 45
- 115
- 116
- 114
- 101
- 115
- 115
- 45
- 115
- 97
- 10
- 32
- 32
- 32
- 32
- 97
- 112
- 112
- 46
- 107
- 117
- 98
- 101
- 114
- 110
- 101
- 116
- 101
- 115
- 46
- 105
- 111
- 47
- 112
- 97
- 114
- 116
- 45
- 111
- 102
- 58
- 32
- 108
- 105
- 116
- 109
- 117
- 115
- 10
- 114
- 111
- 108
- 101
- 82
- 101
- 102
- 58
- 10
- 32
- 32
- 97
- 112
- 105
- 71
- 114
- 111
- 117
- 112
- 58
- 32
- 114
- 98
- 97
- 99
- 46
- 97
- 117
- 116
- 104
- 111
- 114
- 105
- 122
- 97
- 116
- 105
- 111
- 110
- 46
- 107
- 56
- 115
- 46
- 105
- 111
- 10
- 32
- 32
- 107
- 105
- 110
- 100
- 58
- 32
- 82
- 111
- 108
- 101
- 10
- 32
- 32
- 110
- 97
- 109
- 101
- 58
- 32
- 112
- 111
- 100
- 45
- 105
- 111
- 45
- 115
- 116
- 114
- 101
- 115
- 115
- 45
- 115
- 97
- 10
- 115
- 117
- 98
- 106
- 101
- 99
- 116
- 115
- 58
- 10
- 45
- 32
- 107
- 105
- 110
- 100
- 58
- 32
- 83
- 101
- 114
- 118
- 105
- 99
- 101
- 65
- 99
- 99
- 111
- 117
- 110
- 116
- 10
- 32
- 32
- 110
- 97
- 109
- 101
- 58
- 32
- 112
- 111
- 100
- 45
- 105
- 111
- 45
- 115
- 116
- 114
- 101
- 115
- 115
- 45
- 115
- 97
- 10
- 32
- 32
- 110
- 97
- 109
- 101
- 115
- 112
- 97
- 99
- 101
- 58
- 32
- 100
- 101
- 102
- 97
- 117
- 108
- 116
- 10
