apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: litmus
        applabel: app.kubernetes.io/version=latest
        appkind: deployment
    chaosServiceAccount: container-kill-sa
    experiments:
        - name: container-kill-chaos-operator-ce-chaos-operator
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: chaos-operator
