apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: monitoring
        applabel: alertmanager=kube-prometheus-stack-alertmanager
        appkind: statefulset
    chaosServiceAccount: container-kill-sa
    experiments:
        - name: container-kill-alertmanager-kube-prometheus-stack-alertmanager-alertmanager
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: alertmanager
