apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-network-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: chartmuseum
        applabel: app.kubernetes.io/instance=chartmuseum
        appkind: deployment
    chaosServiceAccount: pod-network-latency-sa
    experiments:
        - name: pod-network-latency-chartmuseum-chartmuseum
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: chartmuseum
