apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: chaos-container-kill-left-leg
  namespace: litmus
spec:
  appinfo:
    appns: 'default'
    applabel: 'app.kubernetes.io/component=podtato-head-left-leg'
    appkind: 'deployment'
  # It can be active/stop
  engineState: 'active'
  chaosServiceAccount: litmus-admin
  experiments:
    - name: container-kill-left-leg
      spec:
        components:
          env: []
