apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: cert-manager
        applabel: app=cert-manager-webhook-ovh
        appkind: deployment
    chaosServiceAccount: pod-cpu-hog-exec-sa
    experiments:
        - name: pod-cpu-hog-cert-manager-webhook-ovh-cert-manager-webhook-ovh
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: cert-manager-webhook-ovh
