apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: cert-manager
        applabel: app=cert-manager-webhook-ovh
        appkind: deployment
    chaosServiceAccount: ""
    experiments:
        - name: pod-cpu-hog-cert-manager-webhook-ovh-cert-manager-webhook-ovh
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: cert-manager-webhook-ovh
