apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: cert-manager
        applabel: app=cert-manager-webhook-ovh
        appkind: deployment
    chaosServiceAccount: ""
    experiments: []
