apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: litmus
        applabel: app.kubernetes.io/name=workflow-controller
        appkind: deployment
    chaosServiceAccount: pod-memory-hog-exec-sa
    experiments:
        - name: pod-mem-hog-litmus-agent-workflow-controller-workflow-controller
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: workflow-controller
