apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: litmus
        applabel: app=workflow-controller
        appkind: deployment
    chaosServiceAccount: pod-cpu-hog-exec-sa
    experiments:
        - name: pod-cpu-hog-workflow-controller-workflow-controller
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: workflow-controller
