apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: monitoring
        applabel: operator.prometheus.io/shard=0
        appkind: statefulset
    chaosServiceAccount: ""
    experiments:
        - name: pod-mem-hog-prometheus-kube-prometheus-stack-prometheus-prometheus
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: prometheus
