apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-network-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: cert-manager
        applabel: release=cert-manager-webhook-ovh
        appkind: deployment
    chaosServiceAccount: pod-network-corruption-sa
    experiments:
        - name: pod-network-corruption-cert-manager-webhook-ovh-cert-manager-webhook-ovh
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: cert-manager-webhook-ovh
