apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: monitoring
        applabel: operator.prometheus.io/shard=0
        appkind: statefulset
    chaosServiceAccount: container-kill-sa
    experiments:
        - name: container-kill-prometheus-kube-prometheus-stack-prometheus-prometheus
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: prometheus
