apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: kube-system
        applabel: k8s-app=kube-dns
        appkind: deployment
    chaosServiceAccount: ""
    experiments:
        - name: pod-cpu-hog-coredns-coredns
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: coredns
