apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Kills a container belonging to an application pod 
kind: ChaosExperiment
metadata:
  name: podtato-head-podtato-hats-container-kill
  labels:
    name: podtato-head-podtato-hats-container-kill
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: chaosexperiment
    app.kubernetes.io/version: latest
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups:
          - ""
          - apps
          - batch
          - apps.openshift.io
          - argoproj.io
          - litmuschaos.io
        resources:
          - jobs
          - pods
          - pods/log
          - events
          - replicationcontrollers
          - deployments
          - statefulsets
          - daemonsets
          - replicasets
          - deploymentconfigs
          - rollouts
          - pods/exec
          - chaosengines
          - chaosexperiments
          - chaosresults
        verbs:
          - create
          - list
          - get
          - update
          - patch
          - delete
          - deletecollection
    image: litmuschaos/go-runner:latest
    imagePullPolicy: Always
    args:
      - -c
      - ./experiments -name container-kill
    command:
      - /bin/bash
    env:
      - name: TARGET_CONTAINER
        value: "server"
      - name: RAMP_TIME
        value: ""
      - name: LIB
        value: "pumba"
      - name: TARGET_PODS
        value: ""
      - name: CHAOS_INTERVAL
        value: "10"
      - name: SIGNAL
        value: "SIGKILL"
      - name: SOCKET_PATH
        value: "/var/run/docker.sock"
      - name: CONTAINER_RUNTIME
        value: "docker"
      - name: TOTAL_CHAOS_DURATION
        value: "20"
      - name: PODS_AFFECTED_PERC
        value: ""
      - name: LIB_IMAGE
        value: "litmuschaos/go-runner:latest"
      - name: SEQUENCE
        value: "parallel"
    labels:
      name: podtato-head-podtato-hats-container-kill
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/component: experiment-job
      app.kubernetes.io/version: latest
