apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: podtato-head
        applabel: app.kubernetes.io/component=podtato-head-main
        appkind: deployment
    chaosServiceAccount: ""
    experiments:
        - name: pod-cpu-hog-podtato-main-podtato-head-main
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: podtato-head-main
