apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: oidc-provider
        applabel: app.kubernetes.io/instance=oidc-dex
        appkind: deployment
    chaosServiceAccount: container-kill-sa
    experiments:
        - name: container-kill-oidc-dex-dex
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: dex
