packageName: minikube-kube-system
experiments:
    - name: container-kill-coredns-coredns
      CSV: container-kill-coredns-coredns.chartserviceversion.yaml
      desc: container-kill-coredns-coredns
    - name: pod-delete-coredns
      CSV: pod-delete-coredns.chartserviceversion.yaml
      desc: pod-delete-coredns
    - name: pod-cpu-hog-coredns-coredns
      CSV: pod-cpu-hog-coredns-coredns.chartserviceversion.yaml
      desc: pod-cpu-hog-coredns-coredns
    - name: pod-mem-hog-coredns-coredns
      CSV: pod-mem-hog-coredns-coredns.chartserviceversion.yaml
      desc: pod-mem-hog-coredns-coredns
    - name: pod-io-stress-coredns-coredns
      CSV: pod-io-stress-coredns-coredns.chartserviceversion.yaml
      desc: pod-io-stress-coredns-coredns
    - name: pod-network-corruption-coredns-coredns
      CSV: pod-network-corruption-coredns-coredns.chartserviceversion.yaml
      desc: pod-network-corruption-coredns-coredns
    - name: pod-network-duplication-coredns-coredns
      CSV: pod-network-duplication-coredns-coredns.chartserviceversion.yaml
      desc: pod-network-duplication-coredns-coredns
    - name: pod-network-loss-coredns-coredns
      CSV: pod-network-loss-coredns-coredns.chartserviceversion.yaml
      desc: pod-network-loss-coredns-coredns
    - name: pod-network-latency-coredns-coredns
      CSV: pod-network-latency-coredns-coredns.chartserviceversion.yaml
      desc: pod-network-latency-coredns-coredns
