apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: litmus
        applabel: app=subscriber
        appkind: deployment
    chaosServiceAccount: pod-memory-hog-exec-sa
    experiments:
        - name: pod-mem-hog-subscriber-subscriber
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: subscriber
