apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: litmus
        applabel: app=workflow-controller
        appkind: deployment
    chaosServiceAccount: ""
    experiments:
        - name: pod-mem-hog-workflow-controller-workflow-controller
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: workflow-controller
