packageName: minikube-litmus
experiments:
    - name: container-kill-litmusportal-mongo-mongo
      CSV: container-kill-litmusportal-mongo-mongo.chartserviceversion.yaml
      desc: container-kill-litmusportal-mongo-mongo
    - name: container-kill-litmus-agent-chaos-exporter-chaos-exporter
      CSV: container-kill-litmus-agent-chaos-exporter-chaos-exporter.chartserviceversion.yaml
      desc: container-kill-litmus-agent-chaos-exporter-chaos-exporter
    - name: container-kill-litmus-agent-chaos-operator-chaos-operator
      CSV: container-kill-litmus-agent-chaos-operator-chaos-operator.chartserviceversion.yaml
      desc: container-kill-litmus-agent-chaos-operator-chaos-operator
    - name: container-kill-litmus-agent-event-tracker-event-tracker
      CSV: container-kill-litmus-agent-event-tracker-event-tracker.chartserviceversion.yaml
      desc: container-kill-litmus-agent-event-tracker-event-tracker
    - name: container-kill-litmus-agent-subscriber-subscriber
      CSV: container-kill-litmus-agent-subscriber-subscriber.chartserviceversion.yaml
      desc: container-kill-litmus-agent-subscriber-subscriber
    - name: container-kill-litmus-agent-workflow-controller-workflow-controller
      CSV: container-kill-litmus-agent-workflow-controller-workflow-controller.chartserviceversion.yaml
      desc: container-kill-litmus-agent-workflow-controller-workflow-controller
    - name: container-kill-litmusportal-frontend-litmusportal-frontend
      CSV: container-kill-litmusportal-frontend-litmusportal-frontend.chartserviceversion.yaml
      desc: container-kill-litmusportal-frontend-litmusportal-frontend
    - name: container-kill-litmusportal-server-graphql-server
      CSV: container-kill-litmusportal-server-graphql-server.chartserviceversion.yaml
      desc: container-kill-litmusportal-server-graphql-server
    - name: container-kill-litmusportal-server-auth-server
      CSV: container-kill-litmusportal-server-auth-server.chartserviceversion.yaml
      desc: container-kill-litmusportal-server-auth-server
    - name: pod-delete-litmusportal-mongo
      CSV: pod-delete-litmusportal-mongo.chartserviceversion.yaml
      desc: pod-delete-litmusportal-mongo
    - name: pod-delete-litmus-agent-chaos-exporter
      CSV: pod-delete-litmus-agent-chaos-exporter.chartserviceversion.yaml
      desc: pod-delete-litmus-agent-chaos-exporter
    - name: pod-delete-litmus-agent-chaos-operator
      CSV: pod-delete-litmus-agent-chaos-operator.chartserviceversion.yaml
      desc: pod-delete-litmus-agent-chaos-operator
    - name: pod-delete-litmus-agent-event-tracker
      CSV: pod-delete-litmus-agent-event-tracker.chartserviceversion.yaml
      desc: pod-delete-litmus-agent-event-tracker
    - name: pod-delete-litmus-agent-subscriber
      CSV: pod-delete-litmus-agent-subscriber.chartserviceversion.yaml
      desc: pod-delete-litmus-agent-subscriber
    - name: pod-delete-litmus-agent-workflow-controller
      CSV: pod-delete-litmus-agent-workflow-controller.chartserviceversion.yaml
      desc: pod-delete-litmus-agent-workflow-controller
    - name: pod-delete-litmusportal-frontend
      CSV: pod-delete-litmusportal-frontend.chartserviceversion.yaml
      desc: pod-delete-litmusportal-frontend
    - name: pod-delete-litmusportal-server
      CSV: pod-delete-litmusportal-server.chartserviceversion.yaml
      desc: pod-delete-litmusportal-server
    - name: pod-cpu-hog-litmusportal-mongo-mongo
      CSV: pod-cpu-hog-litmusportal-mongo-mongo.chartserviceversion.yaml
      desc: pod-cpu-hog-litmusportal-mongo-mongo
    - name: pod-cpu-hog-litmus-agent-chaos-exporter-chaos-exporter
      CSV: pod-cpu-hog-litmus-agent-chaos-exporter-chaos-exporter.chartserviceversion.yaml
      desc: pod-cpu-hog-litmus-agent-chaos-exporter-chaos-exporter
    - name: pod-cpu-hog-litmus-agent-chaos-operator-chaos-operator
      CSV: pod-cpu-hog-litmus-agent-chaos-operator-chaos-operator.chartserviceversion.yaml
      desc: pod-cpu-hog-litmus-agent-chaos-operator-chaos-operator
    - name: pod-cpu-hog-litmus-agent-event-tracker-event-tracker
      CSV: pod-cpu-hog-litmus-agent-event-tracker-event-tracker.chartserviceversion.yaml
      desc: pod-cpu-hog-litmus-agent-event-tracker-event-tracker
    - name: pod-cpu-hog-litmus-agent-subscriber-subscriber
      CSV: pod-cpu-hog-litmus-agent-subscriber-subscriber.chartserviceversion.yaml
      desc: pod-cpu-hog-litmus-agent-subscriber-subscriber
    - name: pod-cpu-hog-litmus-agent-workflow-controller-workflow-controller
      CSV: pod-cpu-hog-litmus-agent-workflow-controller-workflow-controller.chartserviceversion.yaml
      desc: pod-cpu-hog-litmus-agent-workflow-controller-workflow-controller
    - name: pod-cpu-hog-litmusportal-frontend-litmusportal-frontend
      CSV: pod-cpu-hog-litmusportal-frontend-litmusportal-frontend.chartserviceversion.yaml
      desc: pod-cpu-hog-litmusportal-frontend-litmusportal-frontend
    - name: pod-cpu-hog-litmusportal-server-graphql-server
      CSV: pod-cpu-hog-litmusportal-server-graphql-server.chartserviceversion.yaml
      desc: pod-cpu-hog-litmusportal-server-graphql-server
    - name: pod-cpu-hog-litmusportal-server-auth-server
      CSV: pod-cpu-hog-litmusportal-server-auth-server.chartserviceversion.yaml
      desc: pod-cpu-hog-litmusportal-server-auth-server
    - name: pod-mem-hog-litmusportal-mongo-mongo
      CSV: pod-mem-hog-litmusportal-mongo-mongo.chartserviceversion.yaml
      desc: pod-mem-hog-litmusportal-mongo-mongo
    - name: pod-mem-hog-litmus-agent-chaos-exporter-chaos-exporter
      CSV: pod-mem-hog-litmus-agent-chaos-exporter-chaos-exporter.chartserviceversion.yaml
      desc: pod-mem-hog-litmus-agent-chaos-exporter-chaos-exporter
    - name: pod-mem-hog-litmus-agent-chaos-operator-chaos-operator
      CSV: pod-mem-hog-litmus-agent-chaos-operator-chaos-operator.chartserviceversion.yaml
      desc: pod-mem-hog-litmus-agent-chaos-operator-chaos-operator
    - name: pod-mem-hog-litmus-agent-event-tracker-event-tracker
      CSV: pod-mem-hog-litmus-agent-event-tracker-event-tracker.chartserviceversion.yaml
      desc: pod-mem-hog-litmus-agent-event-tracker-event-tracker
    - name: pod-mem-hog-litmus-agent-subscriber-subscriber
      CSV: pod-mem-hog-litmus-agent-subscriber-subscriber.chartserviceversion.yaml
      desc: pod-mem-hog-litmus-agent-subscriber-subscriber
    - name: pod-mem-hog-litmus-agent-workflow-controller-workflow-controller
      CSV: pod-mem-hog-litmus-agent-workflow-controller-workflow-controller.chartserviceversion.yaml
      desc: pod-mem-hog-litmus-agent-workflow-controller-workflow-controller
    - name: pod-mem-hog-litmusportal-frontend-litmusportal-frontend
      CSV: pod-mem-hog-litmusportal-frontend-litmusportal-frontend.chartserviceversion.yaml
      desc: pod-mem-hog-litmusportal-frontend-litmusportal-frontend
    - name: pod-mem-hog-litmusportal-server-graphql-server
      CSV: pod-mem-hog-litmusportal-server-graphql-server.chartserviceversion.yaml
      desc: pod-mem-hog-litmusportal-server-graphql-server
    - name: pod-mem-hog-litmusportal-server-auth-server
      CSV: pod-mem-hog-litmusportal-server-auth-server.chartserviceversion.yaml
      desc: pod-mem-hog-litmusportal-server-auth-server
    - name: pod-io-stress-litmusportal-mongo-mongo
      CSV: pod-io-stress-litmusportal-mongo-mongo.chartserviceversion.yaml
      desc: pod-io-stress-litmusportal-mongo-mongo
    - name: pod-io-stress-litmus-agent-chaos-exporter-chaos-exporter
      CSV: pod-io-stress-litmus-agent-chaos-exporter-chaos-exporter.chartserviceversion.yaml
      desc: pod-io-stress-litmus-agent-chaos-exporter-chaos-exporter
    - name: pod-io-stress-litmus-agent-chaos-operator-chaos-operator
      CSV: pod-io-stress-litmus-agent-chaos-operator-chaos-operator.chartserviceversion.yaml
      desc: pod-io-stress-litmus-agent-chaos-operator-chaos-operator
    - name: pod-io-stress-litmus-agent-event-tracker-event-tracker
      CSV: pod-io-stress-litmus-agent-event-tracker-event-tracker.chartserviceversion.yaml
      desc: pod-io-stress-litmus-agent-event-tracker-event-tracker
    - name: pod-io-stress-litmus-agent-subscriber-subscriber
      CSV: pod-io-stress-litmus-agent-subscriber-subscriber.chartserviceversion.yaml
      desc: pod-io-stress-litmus-agent-subscriber-subscriber
    - name: pod-io-stress-litmus-agent-workflow-controller-workflow-controller
      CSV: pod-io-stress-litmus-agent-workflow-controller-workflow-controller.chartserviceversion.yaml
      desc: pod-io-stress-litmus-agent-workflow-controller-workflow-controller
    - name: pod-io-stress-litmusportal-frontend-litmusportal-frontend
      CSV: pod-io-stress-litmusportal-frontend-litmusportal-frontend.chartserviceversion.yaml
      desc: pod-io-stress-litmusportal-frontend-litmusportal-frontend
    - name: pod-io-stress-litmusportal-server-graphql-server
      CSV: pod-io-stress-litmusportal-server-graphql-server.chartserviceversion.yaml
      desc: pod-io-stress-litmusportal-server-graphql-server
    - name: pod-io-stress-litmusportal-server-auth-server
      CSV: pod-io-stress-litmusportal-server-auth-server.chartserviceversion.yaml
      desc: pod-io-stress-litmusportal-server-auth-server
    - name: pod-network-corruption-litmusportal-mongo-mongo
      CSV: pod-network-corruption-litmusportal-mongo-mongo.chartserviceversion.yaml
      desc: pod-network-corruption-litmusportal-mongo-mongo
    - name: pod-network-corruption-litmus-agent-chaos-exporter-chaos-exporter
      CSV: pod-network-corruption-litmus-agent-chaos-exporter-chaos-exporter.chartserviceversion.yaml
      desc: pod-network-corruption-litmus-agent-chaos-exporter-chaos-exporter
    - name: pod-network-corruption-litmus-agent-chaos-operator-chaos-operator
      CSV: pod-network-corruption-litmus-agent-chaos-operator-chaos-operator.chartserviceversion.yaml
      desc: pod-network-corruption-litmus-agent-chaos-operator-chaos-operator
    - name: pod-network-corruption-litmus-agent-event-tracker-event-tracker
      CSV: pod-network-corruption-litmus-agent-event-tracker-event-tracker.chartserviceversion.yaml
      desc: pod-network-corruption-litmus-agent-event-tracker-event-tracker
    - name: pod-network-corruption-litmus-agent-subscriber-subscriber
      CSV: pod-network-corruption-litmus-agent-subscriber-subscriber.chartserviceversion.yaml
      desc: pod-network-corruption-litmus-agent-subscriber-subscriber
    - name: pod-network-corruption-litmus-agent-workflow-controller-workflow-controller
      CSV: pod-network-corruption-litmus-agent-workflow-controller-workflow-controller.chartserviceversion.yaml
      desc: pod-network-corruption-litmus-agent-workflow-controller-workflow-controller
    - name: pod-network-corruption-litmusportal-frontend-litmusportal-frontend
      CSV: pod-network-corruption-litmusportal-frontend-litmusportal-frontend.chartserviceversion.yaml
      desc: pod-network-corruption-litmusportal-frontend-litmusportal-frontend
    - name: pod-network-corruption-litmusportal-server-graphql-server
      CSV: pod-network-corruption-litmusportal-server-graphql-server.chartserviceversion.yaml
      desc: pod-network-corruption-litmusportal-server-graphql-server
    - name: pod-network-corruption-litmusportal-server-auth-server
      CSV: pod-network-corruption-litmusportal-server-auth-server.chartserviceversion.yaml
      desc: pod-network-corruption-litmusportal-server-auth-server
    - name: pod-network-duplication-litmusportal-mongo-mongo
      CSV: pod-network-duplication-litmusportal-mongo-mongo.chartserviceversion.yaml
      desc: pod-network-duplication-litmusportal-mongo-mongo
    - name: pod-network-duplication-litmus-agent-chaos-exporter-chaos-exporter
      CSV: pod-network-duplication-litmus-agent-chaos-exporter-chaos-exporter.chartserviceversion.yaml
      desc: pod-network-duplication-litmus-agent-chaos-exporter-chaos-exporter
    - name: pod-network-duplication-litmus-agent-chaos-operator-chaos-operator
      CSV: pod-network-duplication-litmus-agent-chaos-operator-chaos-operator.chartserviceversion.yaml
      desc: pod-network-duplication-litmus-agent-chaos-operator-chaos-operator
    - name: pod-network-duplication-litmus-agent-event-tracker-event-tracker
      CSV: pod-network-duplication-litmus-agent-event-tracker-event-tracker.chartserviceversion.yaml
      desc: pod-network-duplication-litmus-agent-event-tracker-event-tracker
    - name: pod-network-duplication-litmus-agent-subscriber-subscriber
      CSV: pod-network-duplication-litmus-agent-subscriber-subscriber.chartserviceversion.yaml
      desc: pod-network-duplication-litmus-agent-subscriber-subscriber
    - name: pod-network-duplication-litmus-agent-workflow-controller-workflow-controller
      CSV: pod-network-duplication-litmus-agent-workflow-controller-workflow-controller.chartserviceversion.yaml
      desc: pod-network-duplication-litmus-agent-workflow-controller-workflow-controller
    - name: pod-network-duplication-litmusportal-frontend-litmusportal-frontend
      CSV: pod-network-duplication-litmusportal-frontend-litmusportal-frontend.chartserviceversion.yaml
      desc: pod-network-duplication-litmusportal-frontend-litmusportal-frontend
    - name: pod-network-duplication-litmusportal-server-graphql-server
      CSV: pod-network-duplication-litmusportal-server-graphql-server.chartserviceversion.yaml
      desc: pod-network-duplication-litmusportal-server-graphql-server
    - name: pod-network-duplication-litmusportal-server-auth-server
      CSV: pod-network-duplication-litmusportal-server-auth-server.chartserviceversion.yaml
      desc: pod-network-duplication-litmusportal-server-auth-server
    - name: pod-network-loss-litmusportal-mongo-mongo
      CSV: pod-network-loss-litmusportal-mongo-mongo.chartserviceversion.yaml
      desc: pod-network-loss-litmusportal-mongo-mongo
    - name: pod-network-loss-litmus-agent-chaos-exporter-chaos-exporter
      CSV: pod-network-loss-litmus-agent-chaos-exporter-chaos-exporter.chartserviceversion.yaml
      desc: pod-network-loss-litmus-agent-chaos-exporter-chaos-exporter
    - name: pod-network-loss-litmus-agent-chaos-operator-chaos-operator
      CSV: pod-network-loss-litmus-agent-chaos-operator-chaos-operator.chartserviceversion.yaml
      desc: pod-network-loss-litmus-agent-chaos-operator-chaos-operator
    - name: pod-network-loss-litmus-agent-event-tracker-event-tracker
      CSV: pod-network-loss-litmus-agent-event-tracker-event-tracker.chartserviceversion.yaml
      desc: pod-network-loss-litmus-agent-event-tracker-event-tracker
    - name: pod-network-loss-litmus-agent-subscriber-subscriber
      CSV: pod-network-loss-litmus-agent-subscriber-subscriber.chartserviceversion.yaml
      desc: pod-network-loss-litmus-agent-subscriber-subscriber
    - name: pod-network-loss-litmus-agent-workflow-controller-workflow-controller
      CSV: pod-network-loss-litmus-agent-workflow-controller-workflow-controller.chartserviceversion.yaml
      desc: pod-network-loss-litmus-agent-workflow-controller-workflow-controller
    - name: pod-network-loss-litmusportal-frontend-litmusportal-frontend
      CSV: pod-network-loss-litmusportal-frontend-litmusportal-frontend.chartserviceversion.yaml
      desc: pod-network-loss-litmusportal-frontend-litmusportal-frontend
    - name: pod-network-loss-litmusportal-server-graphql-server
      CSV: pod-network-loss-litmusportal-server-graphql-server.chartserviceversion.yaml
      desc: pod-network-loss-litmusportal-server-graphql-server
    - name: pod-network-loss-litmusportal-server-auth-server
      CSV: pod-network-loss-litmusportal-server-auth-server.chartserviceversion.yaml
      desc: pod-network-loss-litmusportal-server-auth-server
    - name: pod-network-latency-litmusportal-mongo-mongo
      CSV: pod-network-latency-litmusportal-mongo-mongo.chartserviceversion.yaml
      desc: pod-network-latency-litmusportal-mongo-mongo
    - name: pod-network-latency-litmus-agent-chaos-exporter-chaos-exporter
      CSV: pod-network-latency-litmus-agent-chaos-exporter-chaos-exporter.chartserviceversion.yaml
      desc: pod-network-latency-litmus-agent-chaos-exporter-chaos-exporter
    - name: pod-network-latency-litmus-agent-chaos-operator-chaos-operator
      CSV: pod-network-latency-litmus-agent-chaos-operator-chaos-operator.chartserviceversion.yaml
      desc: pod-network-latency-litmus-agent-chaos-operator-chaos-operator
    - name: pod-network-latency-litmus-agent-event-tracker-event-tracker
      CSV: pod-network-latency-litmus-agent-event-tracker-event-tracker.chartserviceversion.yaml
      desc: pod-network-latency-litmus-agent-event-tracker-event-tracker
    - name: pod-network-latency-litmus-agent-subscriber-subscriber
      CSV: pod-network-latency-litmus-agent-subscriber-subscriber.chartserviceversion.yaml
      desc: pod-network-latency-litmus-agent-subscriber-subscriber
    - name: pod-network-latency-litmus-agent-workflow-controller-workflow-controller
      CSV: pod-network-latency-litmus-agent-workflow-controller-workflow-controller.chartserviceversion.yaml
      desc: pod-network-latency-litmus-agent-workflow-controller-workflow-controller
    - name: pod-network-latency-litmusportal-frontend-litmusportal-frontend
      CSV: pod-network-latency-litmusportal-frontend-litmusportal-frontend.chartserviceversion.yaml
      desc: pod-network-latency-litmusportal-frontend-litmusportal-frontend
    - name: pod-network-latency-litmusportal-server-graphql-server
      CSV: pod-network-latency-litmusportal-server-graphql-server.chartserviceversion.yaml
      desc: pod-network-latency-litmusportal-server-graphql-server
    - name: pod-network-latency-litmusportal-server-auth-server
      CSV: pod-network-latency-litmusportal-server-auth-server.chartserviceversion.yaml
      desc: pod-network-latency-litmusportal-server-auth-server
