apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: monitoring
        applabel: app.kubernetes.io/part-of=kube-prometheus-stack
        appkind: deployment
    chaosServiceAccount: ""
    experiments: []
