apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: monitoring
        applabel: app.kubernetes.io/part-of=kube-prometheus-stack
        appkind: deployment
    chaosServiceAccount: ""
    experiments:
        - name: pod-cpu-hog-kube-prometheus-stack-operator-kube-prometheus-stack
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: kube-prometheus-stack
