apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: monitoring
        applabel: chart=kube-prometheus-stack-20.0.1
        appkind: deployment
    chaosServiceAccount: pod-delete-sa
    experiments:
        - name: pod-delete-kube-prometheus-stack-operator
          spec:
            components:
                env: []
