apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: monitoring
        applabel: operator.prometheus.io/shard=0
        appkind: statefulset
    chaosServiceAccount: pod-delete-sa
    experiments:
        - name: pod-delete-prometheus-kube-prometheus-stack-prometheus
          spec:
            components:
                env: []
