apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: base-github-workflow-ci-cd
        applabel: app.kubernetes.io/instance=base-github-workflow-ci-cd
        appkind: deployment
    chaosServiceAccount: pod-delete-sa
    experiments:
        - name: pod-delete-base-github-workflow-ci-cd
          spec:
            components:
                env: []
