apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: cert-manager
        applabel: app.kubernetes.io/name=webhook
        appkind: deployment
    chaosServiceAccount: container-kill-sa
    experiments:
        - name: container-kill-cert-manager-webhook-cert-manager
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: cert-manager
