apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: litmus
        applabel: app=event-tracker
        appkind: deployment
    chaosServiceAccount: ""
    experiments:
        - name: pod-cpu-hog-event-tracker-litmus-event-tracker
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: litmus-event-tracker
