apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: litmus
        applabel: app=event-tracker
        appkind: deployment
    chaosServiceAccount: pod-cpu-hog-exec-sa
    experiments:
        - name: pod-cpu-hog-event-tracker-litmus-event-tracker
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: litmus-event-tracker
