apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: litmus
        applabel: app=event-tracker
        appkind: deployment
    chaosServiceAccount: ""
    experiments: []
