apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: ingress-nginx
        applabel: app.kubernetes.io/component=controller
        appkind: deployment
    chaosServiceAccount: ""
    experiments:
        - name: pod-cpu-hog-ingress-nginx-controller-controller
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: controller
