apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: monitoring
        applabel: app.kubernetes.io/name=alertmanager
        appkind: statefulset
    chaosServiceAccount: pod-memory-hog-exec-sa
    experiments:
        - name: pod-mem-hog-alertmanager-kube-prometheus-stack-alertmanager-config-reloader
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: config-reloader
