apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: monitoring
        applabel: operator.prometheus.io/shard=0
        appkind: statefulset
    chaosServiceAccount: ""
    experiments: []
