apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: podtato-head
        applabel: app.kubernetes.io/component=podtato-head-right-leg
        appkind: deployment
    chaosServiceAccount: container-kill-sa
    experiments:
        - name: container-kill-podtato-right-leg-podtato-head-right-leg
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: podtato-head-right-leg
