apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: monitoring
        applabel: operator.prometheus.io/name=kube-prometheus-stack-prometheus
        appkind: statefulset
    chaosServiceAccount: pod-io-stress-sa
    experiments:
        - name: pod-io-stress-prometheus-kube-prometheus-stack-prometheus-config-reloader
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: config-reloader
