apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: cert-manager
        applabel: app.kubernetes.io/name=webhook
        appkind: deployment
    chaosServiceAccount: ""
    experiments:
        - name: pod-mem-hog-cert-manager-webhook-cert-manager
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: cert-manager
