apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: monitoring
        applabel: app.kubernetes.io/name=alertmanager
        appkind: statefulset
    chaosServiceAccount: ""
    experiments:
        - name: pod-cpu-hog-alertmanager-kube-prometheus-stack-alertmanager-config-reloader
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: config-reloader
