apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: cert-manager
        applabel: app=cert-manager
        appkind: deployment
    chaosServiceAccount: pod-delete-sa
    experiments:
        - name: pod-delete-cert-manager
          spec:
            components:
                env: []
