apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: litmus
        applabel: app=subscriber
        appkind: deployment
    chaosServiceAccount: ""
    experiments:
        - name: pod-cpu-hog-subscriber-subscriber
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: subscriber
