apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: litmus
        applabel: app.kubernetes.io/component=litmus-database
        appkind: statefulset
    chaosServiceAccount: pod-io-stress-sa
    experiments:
        - name: pod-io-stress-litmusportal-mongo-mongo
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: mongo
