apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: monitoring
        applabel: app.kubernetes.io/name=kube-state-metrics
        appkind: deployment
    chaosServiceAccount: ""
    experiments:
        - name: pod-mem-hog-kube-prometheus-stack-kube-state-metrics-kube-state-metrics
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: kube-state-metrics
