apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: monitoring
        applabel: app.kubernetes.io/name=kube-state-metrics
        appkind: deployment
    chaosServiceAccount: pod-memory-hog-exec-sa
    experiments:
        - name: pod-mem-hog-kube-prometheus-stack-kube-state-metrics-kube-state-metrics
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: kube-state-metrics
