apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: oidc-provider
        applabel: app.kubernetes.io/name=dex
        appkind: deployment
    chaosServiceAccount: ""
    experiments:
        - name: pod-mem-hog-oidc-dex-dex
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: dex
