apiVersion: ""
kind: ""
metadata:
    name: pod-cpu-hog-prometheus-kube-prometheus-stack-prometheus-config-reloader
    labels:
        name: ""
        app.kubernetes.io/part-of: ""
        app.kubernetes.io/component: ""
        app.kubernetes.io/version: ""
spec:
    definition:
        scope: ""
        permissions: []
        image: ""
        imagePullPolicy: ""
        args: []
        command: []
        env: []
        labels:
            name: ""
            app.kubernetes.io/part-of: ""
            app.kubernetes.io/component: ""
            app.kubernetes.io/version: ""
