apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: base-github-workflow-ci-cd
        applabel: app.kubernetes.io/instance=base-github-workflow-ci-cd
        appkind: deployment
    chaosServiceAccount: pod-io-stress-sa
    experiments:
        - name: pod-io-stress-base-github-workflow-ci-cd-base-github-workflow-ci-cd
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: base-github-workflow-ci-cd
