apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: ""
        applabel: ""
        appkind: ""
    chaosServiceAccount: ""
    experiments: []
