apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-network-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: cert-manager
        applabel: app=webhook
        appkind: deployment
    chaosServiceAccount: pod-network-duplication-sa
    experiments:
        - name: pod-network-duplication-cert-manager-webhook-cert-manager
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: cert-manager
