apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: podtato-head
        applabel: app.kubernetes.io/component=podtato-head-right-leg
        appkind: deployment
    chaosServiceAccount: pod-delete-sa
    experiments:
        - name: pod-delete-podtato-right-leg
          spec:
            components:
                env: []
