apiVersion: ""
kind: ""
metadata:
    name: ""
    namespace: ""
spec:
    engineState: ""
    appinfo:
        appns: podtato-head
        applabel: app.kubernetes.io/component=podtato-head-right-leg
        appkind: deployment
    chaosServiceAccount: ""
    experiments:
        - name: pod-mem-hog-podtato-right-leg-podtato-head-right-leg
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: podtato-head-right-leg
