apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: podtato-head
        applabel: app.kubernetes.io/component=podtato-head-left-arm
        appkind: deployment
    chaosServiceAccount: pod-cpu-hog-exec-sa
    experiments:
        - name: pod-cpu-hog-podtato-left-arm-podtato-head-left-arm
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: podtato-head-left-arm
