apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
    name: nginx-chaos
    namespace: default
spec:
    engineState: active
    appinfo:
        appns: kube-system
        applabel: k8s-app=kube-dns
        appkind: deployment
    chaosServiceAccount: container-kill-sa
    experiments:
        - name: container-kill-coredns-coredns
          spec:
            components:
                env:
                    - name: TARGET_CONTAINER
                      value: coredns
